/* modulo 40 - loja virtual - criando helper para inicialização*/

/* modulo 45 - Criando actions e reduces e atualizando os componentes das categorias*/

/*modulo 46 - adicionando actions e reducers e alterando os componentes para integração*/

/* modulo 47 -  integração -  detalhes do produto */

export const REGISTER = 'REGISTER',
	AUTENTICAR_TOKEN = 'AUTENTICAR_TOKEN',
	FETCH_CATEGORIAS = 'FETCH_CATEGORIAS',
	FETCH_LOJA = 'FETCH_LOJA',
	FETCH_PRODUTOS = 'FETCH_PRODUTOS',
	FETCH_CATEGORIA = 'FETCH_CATEGORIA',
	FETCH_PRODUTOS_CATEGORIA = 'FETCH_PRODUTOS_CATEGORIA',
	USER = 'USER',
	FETCH_PESQUISA = 'FETCH_PESQUISA',
	FETCH_PRODUTOS_PESQUISA = 'FETCH_PRODUTOS_PESQUISA',
	FETCH_PRODUTO = 'FETCH_PRODUTO',
	FETCH_PRODUTO_VARIACOES = 'FETCH_PRODUTO_VARIACOES',
	FETCH_PRODUTO_AVALIACOES = 'FETCH_PRODUTO_AVALIACOES',
	NOVA_AVALIACAO = 'NOVA_AVALIACAO',
	SET_CARRINHO = 'SET_CARRINHO',
	CLEAN_CARRINHO = 'CLEAN_CARRINHO',
	FETCH_PRODUTO_CARRINHO = 'FETCH_PRODUTO_CARRINHO',
	FETCH_VARIACAO_CARRINHO = 'FETCH_VARIACAO_CARRINHO',
	FETCH_VALOR_ENTREGA = 'FETCH_VALOR_ENTREGA',
	UPDATE_QTD_CART = 'UPDATE_QTD_CART',
	REMOVE_PRODUTO_CART = 'REMOVE_PRODUTO_CART',
	CLEAN_FRETES = 'CLEAN_FRETES',
	UPDATE_FRETE_CART = 'UPDATE_FRETE_CART';

	

